Modules/Settings/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'as'         => 'admin.',
    'middleware' => ['admin'],
    'namespace'  => 'Admin',
    'prefix'     => 'admin'
], function () {
    Route::get('/settings/files_behavior', 'SettingsController@filesBehavior')->name('settings.files_behavior.index');
    Route::get('/settings/file_types', 'SettingsController@fileTypes')->name('settings.file_types.index');
    Route::resource('/settings', 'SettingsController')->only(['index', 'create', 'edit']);
});

Modules/Settings/Resources/views/form.blade.php
@extends('admin.layouts.master')

@section('content')
    @include('admin.layouts.breadcrumbs')

    <div class="page-title">{{ $title }}</div>

    <form class="form-wrap flex-stretch-start"
          data-edit="{{ route('admin.settings.edit', 0) }}"
          method="@isset($model){{ 'PUT' }}@else{{ 'POST' }}@endisset"
          action="@isset($model){{ route('api.settings.update', $model->id) }}@else{{ route('api.settings.store') }}@endisset">

        {{ csrf_field() }}

        @isset($model)
            <input name="hiddenValue" type="hidden" value="{{ $model->value }}">
        @endisset

        <div class="form-details active">
            <fieldset>
                <legend>Main data</legend>

                <div class="row">
                    <label>
                        <div class="caption">Caption:</div>
                        <input name="caption"
                               class="input-text col-1-2"
                               type="text"
                               value="{{ $model->caption ?? '' }}"
                               placeholder="Caption&hellip;">
                    </label>
                </div>

                <div class="row">
                    <label>
                        <div class="caption">Key:</div>
                        <input name="key"
                               class="input-text col-1-2"
                               type="text"
                               data-changed="0"
                               value="{{ $model->key ?? '' }}"
                               placeholder="Key&hellip;">
                    </label>
                </div>

                <div class="row">
                    <label>
                        <div class="caption">Type:</div>
                        <select name="type" class="col-1-2">
                            <option value="bool" @if(isset($model) && $model->type == 'bool') selected @endif>
                                Boolean
                            </option>
                            <option value="text" @if(isset($model) && $model->type == 'text') selected @endif>
                                Text
                            </option>
                            <option value="string" @if(isset($model) && $model->type == 'string') selected
                                    @elseif(!isset($model)) selected @endif>
                                String
                            </option>
                        </select>
                    </label>
                </div>

                <div class="row">
                    <label>
                        <div class="caption">Value:</div>
                        <div id="valueField"></div>
                    </label>
                </div>
            </fieldset>

            <fieldset>
                <legend>Description</legend>
                <div class="row">
                    <textarea class="textarea-block col-1" name="description">{{ $model->description ?? '' }}</textarea>
                </div>
            </fieldset>
        </div>

        <aside class="form-assistant-wrap">
            <ul class="page-navigation"></ul>

            @if (isset($model))
                <div class="etc-info">
                    <span>Created at:&nbsp;</span>
                    <ins>{{ $model->created }}</ins>
                </div>
                <div class="etc-info">
                    <span>Last update:&nbsp;</span>
                    <ins>{{ $model->updated }}</ins>
                </div>
            @endif

            <div class="save-wrap">
                <button name="save" class="button green" type="submit" title="Save settings data">Save</button>
            </div>
        </aside>
    </form>
@endsection

@section('scripts')
    <script src="{{ asset('js/admin/scripts/settings.min.js') }}" type="text/javascript"></script>
@endsection

Modules/Settings/Resources/views/index.blade.php
@extends('admin.layouts.items-table.default-table')

@section('scripts')
    <script src="{{ asset('js/admin/scripts/settings.min.js') }}" type="text/javascript"></script>
@endsection

Modules/Settings/Resources/views/tab-form.blade.php
@extends('admin.layouts.master')

@section('content')
    @include('admin.layouts.breadcrumbs')

    <div class="page-title">{{ $title }}</div>

    @if (!empty($sections))
        <ul class="tabs-wrap">
            @foreach($sections as $section)
                <li id="{{ $section }}" @if($loop->first) class="active" @endif>
                    @php
                        $section_name = explode('_', $section);
                        $section_name[0] = ucfirst($section_name[0]);
                    @endphp
                    {{ implode(' ', $section_name) }}
                </li>
            @endforeach
        </ul>
    @endif

    <form class="form-wrap flex-stretch-start"
          method="PATCH"
          action="{{ route('api.settings.update', 0) }}"
          data-placement="tabs-form">

        {{ csrf_field() }}

        @if (!empty($sections))
            @foreach($sections as $section)
                <div class="form-details @if($loop->first) active @endif" id="{{ $section }}">
                    @foreach($collection as $model)
                        @if ($model->section == $section)
                            @include('settings::partials.' . $model->type)
                        @endif
                    @endforeach
                </div>
            @endforeach
        @else
            <div class="form-details active">
                @foreach($collection as $model)
                    @include('settings::partials.' . $model->type)
                @endforeach
            </div>
        @endif
    </form>
@endsection

@section('scripts')
    <script src="{{ asset('js/admin/scripts/settings.min.js') }}" type="text/javascript"></script>
@endsection